# Generated by Django 5.2.6 on 2026-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration_minutes', models.PositiveIntegerField(default=20, help_text='Duração máxima da sessão de controlo em minutos.')),
            ],
            options={
                'verbose_name': 'Configurações do Laboratório',
                'verbose_name_plural': 'Configurações do Laboratório',
            },
        ),
    ]
