# Generated by Django 5.2.6 on 2026-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='entry_timeout_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Tempo para o utilizador confirmar entrada após chegar ao início da fila em minutos.'),
        ),
    ]
