# Generated by Django 5.2.6 on 2026-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Numero de aluno'),
        ),
    ]
